Feature/some feature
Afordin/hackafor-2 pull request #72
Opened 2024-04-03 20:59 UTC by colmedev

## Cambios Realizados 🎉

- [ ] feat: Redirects on footer, add hover to redirects on footer

## Describir Cambios
Adding ancord to "Ana Rangel" and "aforcita" and add hover to those ancords

## Visuales (Opcional)

https://github.com/Afordin/hackafor-2/assets/161905693/04a75ca8-0ef4-4ca5-9bf6-e472cec43286

## Lista de Verificación ✅

- [ ] Mi código sigue el estilo de código de este proyecto.
- [ ] Mi cambio requiere una modificación de la documentación.
- [ ] He actualizado la documentación según corresponda.

2024-04-03 21:05 UTC, Zyruks requested changes
Cambios mínimos, buen PR.

Te queda arreglar los conflictos, ya que tienes una versión vieja del footer.

2024-04-03 21:05 UTC, Zyruks commented on src/components/Footer/Footer.tsx
> +    innerCopyRight: cn('custom-underline')
```suggestion

```

Como no es clase de tailwind o UNOCSS puedes ponerlo directo en el elemento html

2024-04-03 21:05 UTC, Zyruks commented on src/components/Footer/Footer.tsx
> +          <a href="https://www.twitch.tv/uxanarangel" className={classes.innerCopyRight}>
```suggestion
          <a href="https://www.twitch.tv/uxanarangel" className="custom-underline">
```

2024-04-03 21:05 UTC, Zyruks commented on src/components/Footer/Footer.tsx
> +          <a href="https://www.twitch.tv/afor_digital" className={classes.innerCopyRight}>
```suggestion
          <a href="https://www.twitch.tv/afor_digital" className="custom-underline">
```

2024-04-03 21:05 UTC, Zyruks commented on src/index.css
> +}
```suggestion
.custom-underline::before {
  position: absolute;
  width: 100%;
  height: 2px;
  inset-inline: 0;
  bottom: 0;
  content: '';
  border-radius: 30%;
  transform: scaleX(0);
  background-color: #fff;
  transition: transform 0.3s ease-out;
}
```

Solo para acortar un poco y aprendan un poco de operadores

Referencia de [Operadores Logicos](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_logical_properties_and_values)

2024-04-03 21:08 UTC, colmedev commented on src/components/Footer/Footer.tsx
> +    innerCopyRight: cn('custom-underline')
si vi la nueva version del footer pero no se porque se conservo la vieja

2024-04-03 21:09 UTC, Zyruks commented
En el titulo Feature/some feature no es muy descriptivo.

Una idea seria

`Feature / Add Hover State to footer anchor links`

Por Dar una idea

2024-04-03 21:28 UTC, Zyruks commented on src/components/Footer/Footer.tsx
> +    innerCopyRight: cn('custom-underline')
# Actualizar tu rama de característica con los cambios más recientes de la rama principal

Sigue estas instrucciones para asegurarte de que tu rama de característica (feature/some-feature) esté actualizada con los últimos cambios de la rama principal (main). Esto te ayudará a evitar conflictos y mantener tu trabajo en sincronía con el resto del equipo.

## Cambia a la rama principal:
Primero, asegúrate de estar en la rama principal para poder traer los últimos cambios. Abre tu terminal y ejecuta:

```bash
git checkout main
```

## Actualiza la rama principal:
Ahora, actualiza tu rama principal local con los últimos cambios del repositorio remoto. Puedes hacer esto de dos maneras. Si estás trabajando directamente sobre el repositorio original, simplemente ejecuta:


```bash
git pull
```
O
```bash
git pull origin main
```

## Vuelve a tu rama de característica:
Cambia de nuevo a tu rama de característica para aplicarle los cambios de la rama principal.

```bash
git checkout feature/some-feature
```
Utiliza rebase para integrar los cambios de la rama principal a tu rama de característica. Esto te ayuda a crear una historia más limpia.

```bash
git rebase main
```

## Publica los cambios en tu rama:

Después de hacer rebase, es posible que necesites forzar el push de tu rama al repositorio remoto, especialmente si ya habías hecho push de tu rama antes del rebase. Usa el comando push con precaución para evitar sobrescribir el trabajo de otros. `--force-with-lease` es más seguro que `--force` porque previene la sobrescritura si hay cambios que no has visto.

```bash
git push --force-with-lease upstream feature/some-feature
```

#### Nota: Asegúrate de reemplazar uspstream con el nombre de tu remoto si estás trabajando con un fork y has configurado un remoto diferente para tu fork.

#### Importante: Siempre verifica si hay cambios en el repositorio remoto antes de hacer un push, especialmente si planeas usar `--force` o `--force-with-lease`. Y recuerda reemplazar upstream con los nombres que hayas utilizado para los remotos en tu configuración de Git.

2024-04-03 22:50 UTC, colmedev commented on src/components/Footer/Footer.tsx
> +          <a href="https://www.twitch.tv/uxanarangel" className={classes.innerCopyRight}>
Done

2024-04-03 22:50 UTC, colmedev commented on src/components/Footer/Footer.tsx
> +    innerCopyRight: cn('custom-underline')
Done

2024-04-03 22:51 UTC, colmedev commented on src/components/Footer/Footer.tsx
> +          <a href="https://www.twitch.tv/afor_digital" className={classes.innerCopyRight}>
Done

2024-04-03 23:02 UTC, Zyruks approved these changes
Listo el PR

![SonicBoomKnucklesGIF](https://github.com/Afordin/hackafor-2/assets/14036522/dc6c500f-d927-42cd-b545-0d6a53b55da4)

2024-04-04 08:25 UTC, afordigital commented
Gooooood PR and Gooood review zyruks! it looks very great! 😁

2024-04-04 08:25 UTC, merged