feat: Add page 404  ✨
Afordin/hackafor-2 pull request #94
Opened 2024-04-07 03:02 UTC by LUISEDOCCOR

## Add page 404
![image](https://github.com/Afordin/hackafor-2/assets/110699874/fd2dfee5-8239-425c-b698-4358e0ad62a1)
----------
![image](https://github.com/Afordin/hackafor-2/assets/110699874/5d13ebaa-3833-4cf7-94d3-dbfa4254be0a)

2024-04-07 17:17 UTC, Zyruks requested changes
Looks really good, minor changes and is approve :3

2024-04-07 17:17 UTC, Zyruks commented on src/pages/NotFound/NotFound.tsx
> +          <h3 className="text-4xl font-semibold">PÁGINA NO ENCONTRADA</h3>
```suggestion
          <h2 className="text-4xl font-semibold">PÁGINA NO ENCONTRADA</h2>
```

Seguimos los `heading`, de `h1` luego va `h2`

2024-04-07 17:17 UTC, Zyruks commented on src/pages/NotFound/NotFound.tsx
> +      <main className="relative z-2 w-full max-w-7xl mx-auto px-5 flex flex-col justify-center items-center h-[87vh] text-cWhite font-dmsans gap-16">
```suggestion
      <main className="relative z-2 w-full max-w-7xl mx-auto px-5 flex flex-col justify-center items-center h-[87svh] text-cWhite font-dmsans gap-16">
```

Con `svh` también hacemos que se vea bien en mobile

2024-04-07 17:17 UTC, Zyruks commented on src/pages/NotFound/NotFound.tsx
> +          </Button>
```suggestion
   
  <Link to={ROUTE.home}>
    <Button size={ButtonSize.xl} variant={VARIANT.GHOST} onClick={() => {}} className="flex gap-2 items-center">
      <span>IR A INICIO</span>
      <div className="i-lucide:arrow-up-right  w-8 h-8 bg-gradient-to-rb from-primary-600 to-secondary-500" />
    </Button>
  </Link>
         
```

Esta no estoy totalmente seguro, deberías revisarla.

Si Link está dentro de `Button` cuando cliqueas y no es el texto no pasa nada.

2024-04-07 17:22 UTC, Zyruks commented
The CI for Commitlint got a error too,

![image](https://github.com/Afordin/hackafor-2/assets/14036522/473b7560-879f-48f2-b85f-f82b74bc867e)


You got a commit that is not using the conventional commit structure

![image](https://github.com/Afordin/hackafor-2/assets/14036522/f9cf851d-2ae7-4042-badf-c6fa832febb7)

You can edit this commit, if you need help just let me know.

2024-04-07 20:13 UTC, afordigital commented
Very goood PR and very good review! Agree with Zyruks, minor changes approved and its merged!

2024-04-07 22:51 UTC, LUISEDOCCOR commented
Thanks Zyruks! ✨But I need some help to change the name to the commit please 🙌

2024-04-08 02:29 UTC, juanpablo-is commented
There are several ways, since it is not a commit so far down, you can do:

`git reset d0bdffda5e319d3cb8ac280ec64160b7216da0f1`
`git commit --amend -m "feat: update routes.ts"`
`git add .`
`git commit -m "feat: add wildcard route for 404 error"`

2024-04-08 02:40 UTC, LUISEDOCCOR commented
Thank you so much @juanpablo-is 🙌

2024-04-08 15:45 UTC, closed without merging